[project]
name = "ndtools"
version = "1.1.0"
description = "Collection of tools to extend multidimensional array operations"
readme = "README.md"
keywords = [
    "comparison",
    "duck-array",
    "ndarray",
    "numpy",
    "pandas",
    "xarray",
]
requires-python = ">=3.10,<4.0"
dependencies = [
    "numpy>=2",
    "pandas>=2",
    "typing-extensions>=4",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[[project.authors]]
name = "Akio Taniguchi"
email = "a-taniguchi@mail.kitami-it.ac.jp"

[project.license]
file = "LICENSE"

[project.urls]
homepage = "https://astropenguin.github.io/ndtools"
repository = "https://github.com/astropenguin/ndtools"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25,<27",
    "ipython>=8,<10",
    "myst-parser>=4,<6",
    "pandas-stubs>=2",
    "pydata-sphinx-theme>=0.16,<1.0",
    "pyright>=1,<2",
    "pytest>=8,<10",
    "sphinx>=8,<10",
]


[tool.pyright]
typeCheckingMode = "strict"
